from pathlib import Path

ROOT = Path(__file__).parent

AREA_WIDTH, AREA_HEIGHT = 800, 600
STATUSBAR_HEIGHT = 100

BG_COLOR = (24, 24, 28)

SCREEN_WIDTH = AREA_WIDTH
SCREEN_HEIGHT = AREA_HEIGHT + STATUSBAR_HEIGHT
